name = "Fetch"
uuid = "bb354801-46f6-40b6-9c3d-d42d7a74c775"
authors = ["JingYu Ning <foldfelis@gmail.com> and contributors"]
version = "0.1.0"

[deps]
DataDeps = "124859b0-ceae-595e-8997-d05f6a7a8dfe"
Dates = "ade2ca70-3891-5945-98fb-dc099432e06a"
HTTP = "cd3eb016-35fb-5094-929b-558a96fad6f3"
Random = "9a3f8284-a2c9-5f02-9a11-845980a1fd5c"

[compat]
DataDeps = "0.7"
julia = "1.6"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
